---
title: "Depresset. Grupo 6. Visualización"
author: "Daniel Galván Cancio, Daniel Vela Gamacho, Jaime Linares Barrera, Miguel Encina Martinez"
output: html_document
---

# Proyecto sobre la depresión estudiantil

```{r cars}
# Cargar las librerías
  library(readr)
  library(tidyr)
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
  library(lubridate)
  library(gapminder)
  library(plotly)

```


```{r cars}
  # leer el csv
  ds <- read.csv("./data/student_depression_dataset.csv",sep=",")
  head(ds)
  dim(ds)

```

## Depresión por sexo

```{r cars}

  depresion_por_sexo <- ds %>%
  group_by(Gender) %>%
  summarise(
    Numero_Estudiantes_Deprimidos = sum(Depression == 1, na.rm = TRUE),
    Numero_Estudiantes_No_Deprimidos = sum(Depression == 0, na.rm = TRUE)
  ) %>%
  mutate(
    Total = Numero_Estudiantes_Deprimidos + Numero_Estudiantes_No_Deprimidos,
    Porcentaje_Deprimidos = 100 * Numero_Estudiantes_Deprimidos / Total,
    Porcentaje_No_Deprimidos = 100 * Numero_Estudiantes_No_Deprimidos / Total
  )


depresion_por_sexo

```

## Depresión por ciudad

```{r cars}

profesions <- ds %>%
  group_by(Profession) %>%
  summarise(Count = n())

profesions

ggplot(profesions, aes(x = reorder(Profession, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "coral") +
  labs(title = "Número de Personas por Profesión",
       x = "Profesión",
       y = "Número de Personas") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## Depresión por nivel de estudios


